import { NextRequest, NextResponse } from "next/server";

import { getOpenAIClient, hasOpenAIConfig } from "@/lib/sscp/openai";
import { NarrationRequest } from "@/lib/sscp/types";

export const runtime = "nodejs";

function bad(error: string, status = 400) {
  return NextResponse.json({ ok: false, error }, { status });
}

export async function POST(req: NextRequest) {
  let body: NarrationRequest | null = null;
  try {
    body = await req.json();
  } catch {
    return bad("Invalid JSON payload.");
  }

  if (!body?.text?.trim()) return bad("Narration text is required.");
  if (body.text.length > 4096) {
    return bad("Narration text exceeds the 4096 character limit for one clip.");
  }

  if (!hasOpenAIConfig()) {
    return bad("AI narration is not configured. Use the browser read-aloud option instead.", 503);
  }

  try {
    const client = getOpenAIClient();
    const response = await client.audio.speech.create({
      model: "gpt-4o-mini-tts",
      voice: body.voice ?? "cedar",
      input: body.text,
      response_format: body.format ?? "mp3",
      speed: body.speed ?? 1,
      ...(body.instructions ? { instructions: body.instructions } : {}),
    });
    const arrayBuffer = await response.arrayBuffer();
    const base64 = Buffer.from(arrayBuffer).toString("base64");
    const mimeType =
      body.format === "wav"
        ? "audio/wav"
        : body.format === "aac"
          ? "audio/aac"
          : "audio/mpeg";

    return NextResponse.json({
      ok: true,
      mimeType,
      data: base64,
      disclosure: "This audio was generated by AI.",
    });
  } catch (error: any) {
    return bad(error?.message ?? "Failed to generate narration.", 500);
  }
}
